name: shared_dependencies
description: Defines versions of shared dependencies
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Runtime dependencies
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  go_router: ^7.0.1
  injectable: ^2.1.1
  json_annotation: ^4.8.1
  collection: ^1.17.1

  # Dev dependencies
  # ⚠️ These dependencies should NEVER be used as normal dependencies but only
  # used in a dev_dependencies block
  # We define them here to define a common version
  alchemist: ^0.6.0
  build_runner: ^2.4.4
  dart_code_metrics: ^5.7.4
  flutter_gen_runner: ^5.3.1
  freezed: ^2.3.4
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
