arb-dir: lib/common/l10n/translations
output-dir: lib/common/l10n/generated
template-arb-file: app_fr.arb
output-localization-file: l10n.dart
output-class: L10N
nullable-getter: false
synthetic-package: false